### ISSUE TITLE
I do not see tabs open for each new request

### ISSUE THREAD

**Issue by smiller0924** [NickRimmer/insomnia-plugin-request-navigator#25] opened 2023-09-12 17:24 UTC
When I click a new request in Insomnia it does not open as a tab.  Is there a configuration function that I need to setup?

**Comment by NickRimmer** [comment] 2023-09-13 11:43
Hi @smiller0924,
Could you please confirm you are using the latest versions of Insomnia and Plugin? Recently Insomnia had a major update and changed a lot in background

**Comment by Nerwin** [comment] 2023-09-15 20:36
I have the same issue, it was working well before the recent major update of insomnia.
I have the latest Insomnia version and the latest version of the plugin.
A tab is showing when starting Insomnia, but as soon as i click a new request, the whole tab bar disappears

**Comment by NickRimmer** [comment] 2023-09-25 18:08
When the application started and you faced such issue, could you please open dev tools (ctrl+alt+i) and send me example if there are any errors.

Unfortunately, I cannot reproduce it and I need you help (=

**Comment by smiller0924** [comment] 2023-09-25 19:37
That's the thing.  There are no errors.  It just doesn't run.  Not sure what you are looking for from the DEV Tools.  If you give me an idea I could narrow it down for you and send you what you need.  Thank you.

**Comment by jeanchristopheMICHEL** [comment] 2023-09-27 06:53
After upgrade from V2023.5.5 to v2023.5.8, tabs are now availble. I hope that this post can help you

**Comment by lmorganl** [comment] 2023-09-28 07:03
Plugin is not working again with 8.0 :(

**Comment by smiller0924** [comment] 2023-10-02 12:47
I'm on Insomnia 2023.5.8.  the plug in does not work.  How do you engage it?  Is there a trigger of a setting in the plugin?  You instructions are a bit sparse on the details.

Thank you.

**Comment by lmorganl** [comment] 2023-10-02 15:28
in 2023.5.8 after each start i need to click on menu : tools/reload plugins

**Comment by Pimpnase** [comment] 2023-10-06 06:44
Same with Insomnia v8.2.0. The plugin isn't loaded on startup and doesn't show tabs at all. Only a manual refresh via Tools → Reload Plugins, as @lmorganl state does show the tabs (and then it works wonderfully). They also appear, if you open Preferences → Plugins, but my guess is, that they reload the plugins when showing the page, so same problem.


The problem only exist when starting/opening Insomnia. Once the plugin is loaded, it works without problems. On startup there is the following error in the dev-tools console:
```
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'props')
    at initRouter (/Users/[USER]/Library/Application Support/Insomnia/plugins/insomnia-plugin-request-navigator/index.js:2771:72)
    at connect (/Users/[USER]/Library/Application Support/Insomnia/plugins/insomnia-plugin-request-navigator/index.js:2912:8)
    at waitForConnectionAsync (/Users/[USER]/Library/Application Support/Insomnia/plugins/insomnia-plugin-request-navigator/index.js:3726:8)
    at sentryWrapped (helpers.ts:98:17)
```

**Comment by alexander-veshkin** [comment] 2023-10-14 13:05
Same for me, but could not see any tabs - tried to reload plugins, disable all plugins exept this, clean storage.
ins 8.2.0 

```
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'props')
    at initRouter (/Users/[USER]/Library/Application Support/Insomnia/plugins/insomnia-plugin-request-navigator/index.js:2771:72)
    at connect (/Users/[USER]/Library/Application Support/Insomnia/plugins/insomnia-plugin-request-navigator/index.js:2912:8)
    at waitForConnectionAsync (/Users/[USER]/Library/Application Support/Insomnia/plugins/insomnia-plugin-request-navigator/index.js:3726:8)
    at sentryWrapped (helpers.ts:98:17)
```

**Comment by NickRimmer** [comment] 2023-10-14 13:53
> Plugin is not working again with 8.0 :(

I will try to look into it, but unfortunately Kong's team not allowing me to continue using fully Insomnia from version 8... I simply cannot login or share anything to their cloud

**Comment by lmorganl** [comment] 2023-10-17 13:35
https://github.com/Kong/insomnia/releases/tag/core%408.3.0
back in 8.3 :)

**Comment by smiller0924** [comment] 2023-10-18 20:11
Imorganl,

I'm kind of a noob with Insomnia. Which package do I download and how do I
install it?

Thank you.

**Comment by lmorganl** [comment] 2023-10-19 07:29
Hello Smiller0924

insomnia-plugin-request-navigator is also working with Insomnia 8.3 [insomnia-plugin-request-navigator](https://github.com/Kong/insomnia/releases/  but only on Local Scratch Pad 
v2023.5.8 is also availlable on github.

**Comment by smiller0924** [comment] 2023-10-21 12:04
Nick,

Thank you. But I still need to know how to make it work. Any ideas?

Thank you

S.

**Comment by w33ble** [comment] 2023-11-07 16:37
Hitting this as well, error is coming from this line:

`internalRouter = rootElement[containerElement].memoizedState.element.props.router;`

Looks like `rootElement[containerElement].memoizedState.element` here is null, but I don't know enough about Insomnia plugins to know what the actual issue is. Running Insomnia 8.3.0 and version 0.3.0 of this plugin.

**Comment by LunaticoCR** [comment] 2023-11-07 17:04
Same here, v8.3.0 on macOS and no tab unfortunately.

**Comment by bitcrumb** [comment] 2023-12-06 08:38
Same here, never seeing the tabs on startup.

I always have to go to the pluing settings and disable/enable the plugin for them to appear.

**Comment by bitcrumb** [comment] 2023-12-06 08:41
This is the log after startup in which I can see an error and a warning relating to request-navigator:

![Screenshot 2023-12-06 at 09 39 56](https://github.com/NickRimmer/insomnia-plugin-request-navigator/assets/135126/6b9a8846-90b7-4a22-8ae8-68577ed8eac8)

These are the continued logs after disabling/enabling the plugin (after which the tabs work/appear):
![Screenshot 2023-12-06 at 09 40 33](https://github.com/NickRimmer/insomnia-plugin-request-navigator/assets/135126/e97875af-4e31-48e4-927c-750111bdb0a8)

Looks indeed that this is about this line: https://github.com/NickRimmer/insomnia-plugin-request-navigator/blob/31f1c8f19d57699334696dd916957236644f8833/src/services/insomnia/connector/refs-router.ts#L20 as @w33ble correctly identified.

**Comment by bitcrumb** [comment] 2023-12-06 09:20
@NickRimmer I've opened up a pull request to work around this issue, see: https://github.com/NickRimmer/insomnia-plugin-request-navigator/pull/28

This PR implements a (albeit arbitrary) delay to the `initRouter` method. From the error above it is clear that the plugin is loaded/executed before some required elements are present in the page.

This is not clean solution to the problem. However I am not up-to-speed with the implementation details of Insomnia and its plugins. So this is my attempt at working around it. It hink ideally some kind of lifecycle or DOM event is observed before setting/looking up the router?

Hoping you want to take a look at this and validate my workaround?
This would make this plugin a lot more usable for quite a few users apparently!

Thanks for your efforts so far! 🤟🏻

**Comment by bitcrumb** [comment] 2023-12-06 09:36
For anyone looking for a quick fix ⬇️

I've added the workaround to the plugin code and ZIP'ed it up. Just replace the `insomnia-plugin-request-navigator` folder in the plugins directory.

[insomnia-plugin-request-navigator.zip](https://github.com/NickRimmer/insomnia-plugin-request-navigator/files/13579070/insomnia-plugin-request-navigator.zip)

**Comment by NickRimmer** [comment] 2024-10-27 11:02
Hey! Just a heads-up that I'm closing old tickets and archiving this repo. I've started working on my own client, where I'll be applying all the ideas I wanted to bring here 😊

It's called [RestApia](https://www.restapia.app/). Feel free to check it out!

**Closed as completed by NickRimmer** 2024-10-27 11:02 UTC
Labels: investigation
